Repository AngryMaciek/hypercomplex, pull requests merged in 2023-05, with the labels that each got.

#40 docs: add hash footnote
  paper.md
Labels: documentation

#42 ci: upgrade macOS version
  .github/workflows/include.yml
  .github/workflows/install.yml
  .github/workflows/unit.yml
Labels: bug

#44 Proofreading JOSS paper
  paper.md
Labels: enhancement

#45 docs: add editors comments to the references
  paper.bib
  paper.md
Labels: documentation

#46 changes in paper and bib
  paper.bib
  paper.md
Labels: documentation

#48 Patch 2
  paper.bib
  paper.md
Labels: documentation

#54 docs: fix typos
  paper.md
Labels: bug, documentation

#52 feat: implement iterative hypercomplex multiplication
  .github/workflows/docs.yml
  .github/workflows/draft-pdf.yml
  .github/workflows/include.yml
  .github/workflows/install.yml
  .github/workflows/lint.yml
  .github/workflows/unit.yml
  .gitpod.dockerfile
  .test/docs/test.cpp
  .test/unit/test.cpp
  docs/mainpage.dox
  gitpodtest.sh
  hypercomplex/Hypercomplex.hpp
Labels: documentation, enhancement

#56 fix: hypercomplex encryption on large algebras
  .github/workflows/docs.yml
  .github/workflows/unit.yml
  .test/unit/test.cpp
  docs/mainpage.dox
  hypercomplex/Hypercomplex.hpp
  hypercomplex/Makefile
  hypercomplex/Polynomial.hpp
Labels: bug
